name: Auto Login Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug - Environment Info
      run: |
        echo "=== Current Working Directory ==="
        pwd
        echo ""
        echo "=== Files in Root Directory ==="
        ls -la
        echo ""
        echo "=== Search for package.json ==="
        find . -name "package.json" -type f
        echo ""
        echo "=== package.json content (if exists) ==="
        if [ -f "package.json" ]; then
          cat package.json
        else
          echo "package.json not found in current directory"
        fi
        echo ""
        echo "=== Directory Tree ==="
        find . -type f | head -20
