name: Auto Login

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug - List files
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== Files in current directory ==="
        ls -la
        echo "=== Check package.json ==="
        cat package.json || echo "package.json not found"
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run login script
      run: npm start
      env:
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
